from .removeDuplicates.solutions import RemoveDuplicates
from .duplicateZeros.solutions import DuplicateZeros
from .mergeSortArray.solutions import MergeSortArray
from .removeElement.solutions import RemoveElement
from .evenDigitsOfInt.solutions import EvenDigitsOfInt
from .sortedSquares.solutions import SortedSquares
from .minimumTimeToPoints.solutions import MinimumTimeToPoints
from .nAndDoubleExist.solutions import NandDoubleExist
from .validMoutainArray.solutions import ValidMoutainArray